### PR TITLE
Add Target -> GO Edges 👩🏼‍💻

### PR DESCRIPTION
**Pull request by laulopezreal**
This PR adds the code to generate edges between the Target and the GeneOntology nodes.

### CODE REVIEW

**Comment by slobentanzer** [comment]
thanks we'll review ASAP :)

@kpto, maybe a good PR for you to get a better idea of the Open Targets prototype pipeline?

**Comment by kpto** [comment]
I noticed that this PR is repeating changes happened on https://github.com/biocypher/open-targets/pull/12, that PR will needs to be reviewed and merged first then @laulopezreal please rebase your commit later.

**Comment by slobentanzer** [comment]
I just fixed the dependency issue in `pyproject.toml` in [aa64652](https://github.com/biocypher/open-targets/pull/11/commits/aa646528bcda571871d665a2e587d284cef9b296); this should install now. @kpto could you elaborate a little how exactly we should now proceed with the two PRs (order of operations)? Are you saying #12 should be merged first? Where should we merge it? Does it contain the changes made in #11? If so, wouldn't merging it make #11 redundant?

**Comment by slobentanzer** [comment]
@laulopezreal I have briefly reviewed the changes, and programmatically they make sense to me, also the smaller changes that you made.

For the main objective of adding GO edges however, I see only one edge in the output. I am currently travelling, so not sure I can get to the bottom of that soon. We may need to check the way that the edge ID is generated. The log tells us this:

```
2024-10-23 10:15:36,457	DEBUG	module:_core
Duplicate edge IDs encountered: 
    d41d8cd98f00b204e9800998ecf8427e
```

That we only see one edge ID that is deduplicated indicates to me that all edges have the same ID, and so only one edge is ever written. The generated hash should correctly identify all unique relationships that we'd like to have in the graph. Once that is fixed I think we can merge (after reactivating all the commented-out KG parts in the orchestration script).

**Comment by kpto** [comment]
> I just fixed the dependency issue in `pyproject.toml` in [aa64652](https://github.com/biocypher/open-targets/pull/11/commits/aa646528bcda571871d665a2e587d284cef9b296); this should install now. @kpto could you elaborate a little how exactly we should now proceed with the two PRs (order of operations)? Are you saying #12 should be merged first? Where should we merge it? Does it contain the changes made in #11? If so, wouldn't merging it make #11 redundant?

@slobentanzer target_disease_script_extended.py depends on those dependencies and now it will not runs, is it intentional?

Since #12 is just formatting, it could be merged into `main` first then #11 could update from main branch, Git should recalculates the diff and remove those repeated formatting.

I use GitHub desktop, to update a branch from main, on the menu click `Branch` => `Update from main`

**Comment by slobentanzer** [comment]
> target_disease_script_extended.py depends on those dependencies and now it will not runs, is it intentional?

Yes. As I said, this was an example in the context of the paper, and is not maintained, so of limited usefulness. If we get to the point of using imports from other pipelines in the Open Targets pipeline again, we can update those. For now it is fine to put that on hold.

> Since https://github.com/biocypher/open-targets/pull/12 is just formatting, it could be merged into main first

I think it is not. Since 12 is after 11, I think content additions from 11 are also in 12; so, as I said, merging 12 would make 11 redundant. We need to review them in the original order (first the content addition, then the formatting).

**Comment by slobentanzer** [comment]
@kpto good points; do you have a suggestion for a better way of generating a unique ID for each relationship?

While it is true that this is not a "stable" ID, it is far superior to no ID. I'd argue for a technically simple solution. Can't we just hash the individual rows the edge is derived from, however they may appear in the object that is processed?

**Comment by slobentanzer** [comment]
How about for now we generate a hash from the concatenation of ensembl ID and GO term? This at least lets us add additional components to the hashing function if we want to extend the uniqueness criteria later.

**Comment by kpto** [comment]
@slobentanzer The original gene to disease associations was removed, the PR said `add` not `replace`, I suppose this is wrong?

**Comment by slobentanzer** [comment]
@kpto No, they were not removed. They are commented out in the script to save time when testing. However, @laulopezreal changed the implementation of `get_edge_batches()` in the adapter, which breaks the previous implementation of the target-disease relationships.

I have updated the target-disease edge generation (https://github.com/biocypher/open-targets/pull/11/commits/8a9dc5a55057695618e2686547b9bc86cfe53112) to align with @laulopezreal's additions; we need to review whether that's better in terms of performance and intuitiveness of the code, but it seems that the result is the same.

**Comment by slobentanzer** [comment]
@kpto great, thanks a lot for reviewing and fixing the PR. I think test mode on by default is good for development, but users need to be made aware that they need to set it to `False` for the full thing. This is what I write in the last paragraph of the README; do you think this is sufficient?

**Comment by kpto** [comment]
> @kpto great, thanks a lot for reviewing and fixing the PR. I think test mode on by default is good for development, but users need to be made aware that they need to set it to `False` for the full thing. This is what I write in the last paragraph of the README; do you think this is sufficient?

For now it's alright I guess. A better approach would be to implement a command argument for toggling debug mode rather than hard coding it.

Looks good to me now, feel free to merge.

**Review by kpto — APPROVED** [review]
Looks good to me now, feel free to merge.

**Comment by laulopezreal** [comment]
Hi folks! @kpto @slobentanzer 

Sorry for the late reply, I am catching up just now. 

Firstly, thanks a lot for taking the time to look at the changes and provide feedback I really appreciate it!

I'll go through the comments and reach out to you on Zulipchat if I have any questions

**Pull request merged**
