### PR TITLE
Make code flake8, mypy, black and isort compliant 🥸 

### PR DESCRIPTION
**Pull request by laulopezreal**
[pre-commit](https://pre-commit.com/#intro) is a useful tool for managing linters and checking your code for simple errors before comitting. Some advantages are:

Users don't need to install linting tools (other than pre-commit), and tool versions are shared across users / workflows.
pre-commit can be installed locally to prevent committing unless the checks have passed, enforcing a high code quality
Some of the useful built-in hooks are: trim whitespacemypy, pyroma, check-manifest)

### CODE REVIEW

**Comment by slobentanzer** [comment]
very cool @laulopezreal, many thanks!

we don't have pre-commit in the adapters/pipelines so far, so this is a very welcome addition. will review as soon as possible. :)

**Review by kpto — CHANGES_REQUESTED** [review]
@laulopezreal Thanks for your contribution! There are a few issues needed to be sorted.

1. I think you modified the `pyproject.toml` directly, this makes the lock file unsync one will not be able to run `poetry install`. You should run `poetry update {package_name}` to update a package instead.
2. The data folder should be omitted by the formatter/linter as they are resources, not code.
3. The add of file `import.report` seems to be a mistake to me? I think that should be ignored by Git?

These are my initial comments, I will have a more thorough review later.

**Comment by slobentanzer** [comment]
Hi @kpto,
modifying the `pyproject.toml` directly is definitely possible, I don't think that is the reason for the failure. You can usually just run `poetry lock` to update.

**Comment by slobentanzer** [comment]
The dependency issue I get is that the packages we install from our other git repositories still depend on a previous biocypher version (they are defined as `dmb` and `bccb` for the DepMap and CROssBAR repositories). I used these as imports for (originally) demonstrating the workflow of importing adapters from other places on GitHub.

I would suggest to deactivate these imports in the `pyproject.toml`. I have added these changes to the other PR (the first one, #11).

**Comment by kpto** [comment]
@slobentanzer I have never used pre-commit hooks before so I did some research and tried it out but unfortunately I don't think it is a good solution, my reasons are:
1. It significantly slow down time needs to commit, discouraging small commits
2. It forces you to deal with legacy formatting issues right away, therefore distracts you from your current goal
3. It's error message is a pile of text and is not helpful
4. Seems overkill to run linter and formatter for each commit, more efficient if run on PRs
5. Pre-commit is not really enforced because it is manually installed locally so one can still bypass it if they want to

There might be some other hooks that worth running but I don't think formatter and linter are one of them. I think configuring code quality tools in an IDE agnostic way is already enough for now. If we really want to enforce it in the future, we can run them on PR tests. Thoughts?

**Comment by slobentanzer** [comment]
Agree on the comments, generally. We should have some guidelines for formatting, but it is really hard to enforce processing on the contributor's machines. Have you looked into current best practices for aligning contributions in PRs? We do have CI in the BioCypher package that checks the pre-commit there. https://github.com/biocypher/biocypher/blob/85ccf9640d38623c0c13137fdd5f8b99951a13ee/.github/actions/test/action.yaml#L40

Maybe you want to check that out and see what you think about that?

There is of course the question how it is run on the code itself for each commit (or when pushing, etc). Not sure how much should be mandated and how much should be up to the contributor. Personally, I format on save, and run pre-commit manually before I want to merge something or submit a PR, if I remember to do it. If I don't remember to do it, CI fails and I'll then do it in an additional commit, so not sure if that process is perfect, either.

What we can always do is supply the pre-commit configuration as a default, which can then be run by each contributor how they see fit, but also be used by the CI to check code quality.

**Comment by kpto** [comment]
@slobentanzer I think code quality tools shouldn't be run by pre-commit hook. First of all I think we should use Ruff, which is basically the combination of all tools suggested in this PR but written in Rust so it is fast.

Ruff is available as a GitHub action step itself: [https://docs.astral.sh/ruff/integrations/#github-actions](https://docs.astral.sh/ruff/integrations/#github-actions)
Ruff can be configured via pyproject.toml: [https://docs.astral.sh/ruff/configuration/#__tabbed_1_1](https://docs.astral.sh/ruff/configuration/#__tabbed_1_1)

With the above, we
1. provide the rules a contributor should follow, they can choose any mean to comply them
2. enforce the rules in repo level
Pre-commit hook is not needed, I don't see the reason to tie it to a pre-commit hook, what's the advantage?

**Comment by slobentanzer** [comment]
I know that many people use Ruff now; have no opposition. My own experience with pre-commit hooks is a bit mixed, so happy to go with the modern solution. We can test here and then extend to the core packages as well.

**Comment by kpto** [comment]
Closing as discussed above

**Comment by laulopezreal** [comment]
> I know that many people use Ruff now; have no opposition. My own experience with pre-commit hooks is a bit mixed, so happy to go with the modern solution. We can test here and then extend to the core packages as well.

I use Ruff and I agree on Pre-commit comments. I use pre-commit in one of my projects and I just recycled the code.

My experience with ruff is positive and my team is currently migrating towards it and stop using pre-commit. 


My developing workflow is similar to @slobentanzer:
> There is of course the question how it is run on the code itself for each commit (or when pushing, etc). Not sure how much should be mandated and how much should be up to the contributor. Personally, I format on save, and run pre-commit manually before I want to merge something or submit a PR, if I remember to do it. If I don't remember to do it, CI fails and I'll then do it in an additional commit, so not sure if that process is perfect, either.
> 
> What we can always do is supply the pre-commit configuration as a default, which can then be run by each contributor how they see fit, but also be used by the CI to check code quality.

And I definitely am against enforcing code formatting on the developer's local environment. In my view, any contributor should have the freedom to develop as they wish as long as the final Pull Request is compliant with the code rules of the repository.


> @slobentanzer I think code quality tools shouldn't be run by pre-commit hook. First of all I think we should use Ruff, which is basically the combination of all tools suggested in this PR but written in Rust so it is fast and
> 
> 1. Ruff can be configured via pyproject.toml: https://docs.astral.sh/ruff/configuration/#__tabbed_1_1
> 2. Ruff is available as a GitHub action step itself: https://docs.astral.sh/ruff/integrations/#github-actions
> 
> With the above, we
> 
> 1. provide the rules a contributor should follow, they can choose any mean to comply them
> 2. enforce the rules in repo level
> 
> Pre-commit hook is not needed, I don't see the reason to tie it to a pre-commit hook, what's the advantage?

I agree with you guys and I am happy to work on a Pull Request to introduce Ruff if you/we agree on a set of rules for code contributions. What do you think?

**Pull request closed without merging**
